### ISSUE TITLE
7-mode sysstat charts are empty

### ISSUE THREAD

**Issue by mnglora** [AdvUni/picdat#4]
How to reproduce:
Analyse any 7-Mode perfstat output with picdat.

Possible cause:
SYSSTAT_BLOCK_HEADER = 'sysstat_x_1sec' in sysstat_module.py 
Example line for cdot:
=-=-=-=-=-= PERF 10.252.0.26 POSTSTATS =-=-=-=-=-= sysstat_x_1sec 
Example line for 7-mode:
=-=-=-=-=-= PERF filer11 POSTSTATS =-=-=-=-=-= sysstat_1sec.out

**Comment by marloh** [comment]
sysstat_1sec headers are included now
