### ISSUE TITLE
CRCRLF EOL in generated CSVs

### ISSUE THREAD

**Issue by duzzer** [AdvUni/picdat#5]
In every CSV you get a unnecessary blank line, which is caused by having a double carriage return followed by a line feed.

I've tracked the bug down to line 47 of the function create_csv in the file [picdat/table_writer.py](https://github.com/AdvUni/picdat/blob/b8137c9039aa22042c474727ce3209143ec4004e/table_writer.py#L47). 
"os.linesep" is not allowed as line terminator, when you open the file in text mode. 
Source: [docs.python.org](https://docs.python.org/2/library/os.html#os.linesep)

**Comment by marloh** [comment]
Thank you for this hint! I've changed it
